DELETE FROM zalihe;
DELETE FROM izdatnice_st;
DELETE FROM izdatnice_zg;
DELETE FROM primke_st;
DELETE FROM primke_zg;
DELETE FROM error_log;
DELETE FROM artikli;
DELETE FROM mt;
DELETE FROM brojevi;
DELETE FROM skladista;
DELETE FROM dobavljaci;
COMMIT;