-- Artikli --
INSERT INTO ARTIKLI (ID, SIFRA, NAZIV) VALUES ('1', '100101', 'Krastavci 100 g');
INSERT INTO ARTIKLI (ID, SIFRA, NAZIV) VALUES ('2', '100102', 'Paprika 100 g');
INSERT INTO ARTIKLI (ID, SIFRA, NAZIV) VALUES ('3', '100103', 'Jaja 12 kom');
INSERT INTO ARTIKLI (ID, SIFRA, NAZIV) VALUES ('4', '100104', 'Pasteta 10 dag');
INSERT INTO ARTIKLI (ID, SIFRA, NAZIV) VALUES ('5', '100105', 'Sol 1 kg');
INSERT INTO ARTIKLI (ID, SIFRA, NAZIV) VALUES ('6', '100106', 'Secer 1 kg');
INSERT INTO ARTIKLI (ID, SIFRA, NAZIV) VALUES ('7', '100107', 'Papar 10 dag');
INSERT INTO ARTIKLI (ID, SIFRA, NAZIV) VALUES ('8', '100108', 'Maslac 100 g');
INSERT INTO ARTIKLI (ID, SIFRA, NAZIV) VALUES ('9', '100109', 'Vrhnje 300 g');
INSERT INTO ARTIKLI (ID, SIFRA, NAZIV) VALUES ('10', '100110', 'Ajvar 350 g');
INSERT INTO ARTIKLI (ID, SIFRA, NAZIV) VALUES ('11', '100111', 'Cikla 380 g');

-- Dobavljaci --
INSERT INTO DOBAVLJACI (ID, SIFRA, NAZIV, ADRESA) VALUES ('1', '200201', 'Podravka', 'A. Starcevica 32, Koprivnica');
INSERT INTO DOBAVLJACI (ID, SIFRA, NAZIV, ADRESA) VALUES ('2', '200202', 'Agrokor', 'Palisina 43, Zagreb');
INSERT INTO DOBAVLJACI (ID, SIFRA, NAZIV, ADRESA) VALUES ('3', '200203', 'Agrokoka', 'Valmade 13, Pula');
INSERT INTO DOBAVLJACI (ID, SIFRA, NAZIV, ADRESA) VALUES ('4', '200204', 'Zvijezda', 'M. Cavica 1, Zagreb');
INSERT INTO DOBAVLJACI (ID, SIFRA, NAZIV, ADRESA) VALUES ('5', '200205', 'Dukat', 'M. Cavica 9, Zagreb');
INSERT INTO DOBAVLJACI (ID, SIFRA, NAZIV, ADRESA) VALUES ('6', '200206', 'Solana Pag', 'Svilno bb, Pag');
INSERT INTO DOBAVLJACI (ID, SIFRA, NAZIV, ADRESA) VALUES ('7', '200207', 'Luxor', 'Put Majdana bb, Solin');

-- Skladista --
INSERT INTO SKLADISTA (ID, SIFRA, NAZIV) VALUES ('1', '300301', 'Skladiste jedan');
INSERT INTO SKLADISTA (ID, SIFRA, NAZIV) VALUES ('2', '300302', 'Skladiste dva');
INSERT INTO SKLADISTA (ID, SIFRA, NAZIV) VALUES ('3', '300303', 'Skladiste tri');

-- Mjesta troska --
INSERT INTO MT (ID, SIFRA, NAZIV) VALUES ('1', '400401', 'Konoba Franko');
INSERT INTO MT (ID, SIFRA, NAZIV) VALUES ('2', '400402', 'Hotel Sheraton');
INSERT INTO MT (ID, SIFRA, NAZIV) VALUES ('3', '400403', 'Caffe Bar P14');
INSERT INTO MT (ID, SIFRA, NAZIV) VALUES ('4', '400404', 'Caffe Bar Cocolo');